User.create(name: "Ollie", wins: 2, losses: 1, smack_talk: "Show me what you got", budget: 1000000)
User.create(name: "Mike", wins: 4, losses: 1, smack_talk: "Your mom is overweight", budget: 1000000)
User.create(name: "Evans", wins: 1, losses: 10, smack_talk: "It don't make no sense", budget: 1000000)
User.create(name: "Brooke", wins: 100, losses: 0, smack_talk: "You call that a method?", budget: 1000000)

Player.create(name: "LeBron James", team: "Los Angeles Lakers", position: "SF", overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: "Kevin Durant", team: "Golden State Warriors", position: "SF", overall_rating: 97, ppg: 28, off_rating: 99, def_rating: 90, price: 195, user_id: 1, game_id: 1)
Player.create(name: "James Harden", team: "Houston Rockets", position: "SG", overall_rating: 96, ppg: 28, off_rating: 99, def_rating: 88, price: 190, user_id: 1, game_id: 1)
Player.create(name: "Steph Curry", team: "Golden State Warriors", position: "PG", overall_rating: 95, ppg: 28, off_rating: 96, def_rating: 94, price: 200, user_id: 1, game_id: 1)
Player.create(name: Anthony Davis, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Giannis Antetokounmpo, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Kawhi Leonard, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Russell Westbrook, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Kyrie Irving, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Karl-Anthony Towns, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Chris Paul, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Damian Lillard, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: DeMarcus Cousins, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Joel Embiid, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: DeMar DeRozan, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Jimmy Butler, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: John Wall, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Nikola Jokic, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Paul George, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Klay Thompson, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Gordon Hayward, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Kristaps Porzingis, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: LaMarcus Aldridge, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Victor Oladipo, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Andre Drummond, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Ben Simmons, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Bradley Beal, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: C.J. McCollum, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Devin Booker, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
Player.create(name: Donovan Mitchell, team: skjksj, position: kajksj, overall_rating: 98, ppg: 28, off_rating: 99, def_rating: 97, price: 200, user_id: 1, game_id: 1)
