User.create(name_1: "Ollie", name_2: "", wins: 2, losses: 3, budget: 60, smack_talk_1: "Show me what you got", smack_talk_2: "")
User.create(name_1: "Ollie", name_2: "", wins: 2, losses: 3, budget: 60, smack_talk_1: "Show me what you got", smack_talk_2: "")
User.create(name_1: "Ollie", name_2: "", wins: 2, losses: 3, budget: 60, smack_talk_1: "Show me what you got", smack_talk_2: "")
User.create(name_1: "Ollie", name_2: "", wins: 2, losses: 3, budget: 60, smack_talk_1: "Show me what you got", smack_talk_2: "")

Game.create(period_counter: 0, home_score: 0, away_score: 0, game_updates: "It's the end of the first quarter")
Game.create(period_counter: 0, home_score: 10, away_score: 20, game_updates: "It's the end of the second quarter")
Game.create(period_counter: 0, home_score: 30, away_score: 40, game_updates: "It's the end of the third quarter")
Game.create(period_counter: 0, home_score: 45, away_score: 35, game_updates: "It's the end of the fourth quarter")

Team.create(team_name: "", user_id: 1, game_id: 1)
Team.create(team_name: "", user_id: 2, game_id: 2)
Team.create(team_name: "", user_id: 3, game_id: 3)
Team.create(team_name: "", user_id: 4, game_id: 4)

Player.create(name: "LeBron James", player_team: "Los Angeles Lakers", position: "SF", overall_rating: 98, price: 150, ppg: 28, off_rating: 99, def_rating: 97, team_id: 3, points: 0)
Player.create(name: "Kevin Durant", player_team: "Golden State Warriors", position: "SF", overall_rating: 97, ppg: 28, off_rating: 99, def_rating: 90, price: 145, team_id: 3, points: 0)
Player.create(name: "James Harden", player_team: "Houston Rockets", position: "SG", overall_rating: 96, ppg: 28, off_rating: 99, def_rating: 88, price: 145, team_id: 3, points: 0)
Player.create(name: "Steph Curry", player_team: "Golden State Warriors", position: "PG", overall_rating: 95, ppg: 28, off_rating: 96, def_rating: 94, price: 140, team_id: 3, points: 0)
Player.create(name: "Anthony Davis", player_team: "New Orleans Pelicans", position: "PF", overall_rating: 94, ppg: 28, off_rating: 96, def_rating: 86, price: 130, team_id: 3, points: 0)
Player.create(name: "Giannis Antetokounmpo", player_team: "Milwaukee Bucks", position: "SF", overall_rating: 94, ppg: 27, off_rating: 95, def_rating: 93, price: 130, team_id: 3, points: 0)
Player.create(name: "Kawhi Leonard", player_team: "Toronto Raptors", position: "SF", overall_rating: 94, ppg: 16, off_rating: 88, def_rating: 98, price: 130, team_id: 3, points: 0)
Player.create(name: "Russell Westbrook", player_team: "Oklahoma City Thunder", position: "PG", overall_rating: 93, ppg: 25, off_rating: 96, def_rating: 88, price: 130, team_id: 3, points: 0)
Player.create(name: "Kyrie Irving", player_team: "Boston Celtics", position: "PG", overall_rating: 93, ppg: 24, off_rating: 95, def_rating: 92, price: 130, team_id: 3, points: 0)
Player.create(name: "Karl-Anthony Towns", player_team: "Minnesota Timberwolves", position: "C", overall_rating: 91, ppg: 21, off_rating: 90, def_rating: 90, price: 125, team_id: 3, points: 0)
Player.create(name: "Chris Paul", player_team: "Houston Rockets", position: "PG", overall_rating: 90, ppg: 19, off_rating: 90, def_rating: 88, price: 110, team_id: 3, points: 0)
Player.create(name: "Damian Lillard", player_team: "Portland Trail Blazers", position: "PG", overall_rating: 90, ppg: 27, off_rating: 93, def_rating: 85, price: 110, team_id: 3, points: 0)
Player.create(name: "DeMarcus Cousins", player_team: "Golden State Warriors", position: "C", overall_rating: 90, ppg: 25, off_rating: 86, def_rating: 92, price: 110, team_id: 3, points: 0)
Player.create(name: "Joel Embiid", player_team: "Philadelphia 76ers", position: "C", overall_rating: 90, ppg: 23, off_rating: 90, def_rating: 90, price: 110, team_id: 3, points: 0)
Player.create(name: "DeMar DeRozan", player_team: "San Antonio Spurs", position: "SG", overall_rating: 89, ppg: 23, off_rating: 90, def_rating: 86, price: 90, team_id: 3, points: 0)
Player.create(name: "Jimmy Butler", player_team: "Minnesota Timberwolves", position: "SG", overall_rating: 89, ppg: 22, off_rating: 86, def_rating: 91, price: 90, team_id: 3, points: 0)
Player.create(name: "John Wall", player_team: "Washington Wizard", position: "PG", overall_rating: 89, ppg: 20, off_rating: 91, def_rating: 85, price: 90, team_id: 3, points: 0)
Player.create(name: "Nikola Jokic", player_team: "Denver Nuggets", position: "C", overall_rating: 89, ppg: 19, off_rating: 86, def_rating: 88, price: 90, team_id: 3, points: 0)
Player.create(name: "Paul George", player_team: "Oklahoma City Thunder", position: "SF", overall_rating: 89, ppg: 22, off_rating: 86, def_rating: 90, price: 90, team_id: 3, points: 0)
Player.create(name: "Klay Thompson", player_team: "Golden State Warriors", position: "SG", overall_rating: 89, ppg: 20, off_rating: 92, def_rating: 83, price: 90, team_id: 3, points: 0)
Player.create(name: "Gordon Hayward", player_team: "Boston Celtics", position: "SF", overall_rating: 88, ppg: 15, off_rating: 82, def_rating: 88, price: 70, team_id: 3, points: 0)
Player.create(name: "Kristaps Porzingis", player_team: "New York Knicks", position: "C", overall_rating: 88, ppg: 23, off_rating: 86, def_rating: 87, price: 70, team_id: 3, points: 0)
Player.create(name: "LaMarcus Aldridge", player_team: "San Antonio Spurs", position: "PF", overall_rating: 88, ppg: 23, off_rating: 83, def_rating: 86, price: 70, team_id: 3, points: 0)
Player.create(name: "Victor Oladipo", player_team: "Indiana Pacers", position: "SG", overall_rating: 88, ppg: 23, off_rating: 88, def_rating: 80, price: 70, team_id: 3, points: 0)
Player.create(name: "Andre Drummond", player_team: "Detroit Pistons", position: "C", overall_rating: 87, ppg: 15, off_rating: 86, def_rating: 84, price: 40, team_id: 3, points: 0)
Player.create(name: "Ben Simmons", player_team: "Philadelphia 76ers", position: "SF", overall_rating: 87, ppg: 16, off_rating: 87, def_rating: 84, price: 40, team_id: 3, points: 0)
Player.create(name: "Bradley Beal", player_team: "Washington Wizards", position: "SG", overall_rating: 87, ppg: 23, off_rating: 85, def_rating: 84, price: 40, team_id: 3, points: 0)
Player.create(name: "C.J. McCollum", player_team: "Portland Trail Blazers", position: "SG", overall_rating: 87, ppg: 21, off_rating: 85, def_rating: 82, price: 30, team_id: 3, points: 0)
Player.create(name: "Devin Booker", player_team: "Pheonix Suns", position: "SG", overall_rating: 87, ppg: 25, off_rating: 87, def_rating: 82, price: 30, team_id: 3, points: 0)
Player.create(name: "Donovan Mitchell", player_team: "Utah Jazz", position: "SG", overall_rating: 87, ppg: 21, off_rating: 85, def_rating: 84, price: 30, team_id: 3, points: 0)

# Player.create(name: "Ollie Willems", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Michael Schwartz", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Alexandra Aulum-Pedersen", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Chris Bojemski", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Chris Stull", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Johnny Soong", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Johrten Sternberg", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Jordan Farkas", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Mariel Schlaefer", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "May Kim", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Miriam Frank", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Nicky Liu", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Taylor Young", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Thomas Lever", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Brooke Yalof", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Evans Wang", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Matt Lawford", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Charlie Russo", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Daniel Jung", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Daniel Walz", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "JinAi Yap", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Sean Para", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Sebastian Krolkiewicz", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
# Player.create(name: "Sin Nam", player_team: "It_Don't_Make_No_Sense", position: "Point Guard... probably", overall_rating: 0, ppg: 0, off_rating: 0, def_rating: 0, price: 0, team_id: 3, points: 0)
